services:
  frontend:
    build: frontend
    ports:
      - "80:80"

  todo-api-service:
    build: backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=database
      - MYSQL_USER=abdil
      - MYSQL_PWD=my-secret-pw
      - MYSQL_DB=mydb
    depends_on:
      - database
    env_file:
      - ./backend/.env
  database:
    image: mysql:8.0.30-debian
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=ali
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=my-secret-pw
    volumes:
      - ./sqlscripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

volumes:
  dbdata: